//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_job_execution_params
    {
        public long JOB_EXECUTION_ID { get; set; }
        public string TYPE_CD { get; set; }
        public string KEY_NAME { get; set; }
        public string STRING_VAL { get; set; }
        public Nullable<System.DateTime> DATE_VAL { get; set; }
        public Nullable<long> LONG_VAL { get; set; }
        public Nullable<double> DOUBLE_VAL { get; set; }
        public string IDENTIFYING { get; set; }
    
        public virtual batch_job_execution batch_job_execution { get; set; }
    }
}
