//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_step_execution
    {
        public long STEP_EXECUTION_ID { get; set; }
        public long VERSION { get; set; }
        public string STEP_NAME { get; set; }
        public long JOB_EXECUTION_ID { get; set; }
        public System.DateTime START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public string STATUS { get; set; }
        public Nullable<long> COMMIT_COUNT { get; set; }
        public Nullable<long> READ_COUNT { get; set; }
        public Nullable<long> FILTER_COUNT { get; set; }
        public Nullable<long> WRITE_COUNT { get; set; }
        public Nullable<long> READ_SKIP_COUNT { get; set; }
        public Nullable<long> WRITE_SKIP_COUNT { get; set; }
        public Nullable<long> PROCESS_SKIP_COUNT { get; set; }
        public Nullable<long> ROLLBACK_COUNT { get; set; }
        public string EXIT_CODE { get; set; }
        public string EXIT_MESSAGE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
    
        public virtual batch_job_execution batch_job_execution { get; set; }
        public virtual batch_step_execution_context batch_step_execution_context { get; set; }
    }
}
