//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class calling_offers
    {
        public string Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public int Minutes { get; set; }
        public bool Local { get; set; }
        public bool National { get; set; }
        public bool Mobile { get; set; }
        public string CallingRegionId { get; set; }
        public bool IsActive { get; set; }
        public int OperatorId { get; set; }
    }
}
