//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class calling_charge_records
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public calling_charge_records()
        {
            this.calling_records = new HashSet<calling_records>();
        }
    
        public string Id { get; set; }
        public string ServiceId { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public double Cost { get; set; }
        public double Charge { get; set; }
        public int AccountId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public System.DateTime OperatedDate { get; set; }
    
        public virtual account account { get; set; }
        public virtual service service { get; set; }
        public virtual invoice invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calling_records> calling_records { get; set; }
    }
}
