//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class calling_records
    {
        public string Id { get; set; }
        public string FileId { get; set; }
        public string OriNumber { get; set; }
        public string DesNumber { get; set; }
        public string AreaPrefix { get; set; }
        public string AreaName { get; set; }
        public string Type { get; set; }
        public bool IsMobile { get; set; }
        public System.DateTime CallStart { get; set; }
        public int Duration { get; set; }
        public double Cost { get; set; }
        public double RatePerMinute { get; set; }
        public int ChargeMinute { get; set; }
        public double Charge { get; set; }
        public Nullable<int> ActualChargeMiute { get; set; }
        public Nullable<double> ActualCharge { get; set; }
        public string OfferId { get; set; }
        public string ServiceId { get; set; }
        public string PhoneType { get; set; }
        public string ChargeRecordId { get; set; }
        public bool Ignored { get; set; }
        public Nullable<int> IgnoredBy { get; set; }
        public string Description { get; set; }
        public string Warning { get; set; }
        public string Memo { get; set; }
    
        public virtual calling_charge_records calling_charge_records { get; set; }
        public virtual external_bill_files external_bill_files { get; set; }
        public virtual service service { get; set; }
        public virtual service_usage_offers service_usage_offers { get; set; }
    }
}
