//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class external_bill_addon_converters
    {
        public string Id { get; set; }
        public string Keywords { get; set; }
        public string DisplayAs { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> IsDisplay { get; set; }
    }
}
