//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewEntities : DbContext
    {
        public NewEntities()
            : base("name=NewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account_balance_records> account_balance_records { get; set; }
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<addon_charge_records> addon_charge_records { get; set; }
        public virtual DbSet<adjustment> adjustments { get; set; }
        public virtual DbSet<branch> branches { get; set; }
        public virtual DbSet<calling_charge_records> calling_charge_records { get; set; }
        public virtual DbSet<calling_international_region_details> calling_international_region_details { get; set; }
        public virtual DbSet<calling_international_regions> calling_international_regions { get; set; }
        public virtual DbSet<calling_offers> calling_offers { get; set; }
        public virtual DbSet<calling_rates_pstn> calling_rates_pstn { get; set; }
        public virtual DbSet<calling_records> calling_records { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<equipment_models> equipment_models { get; set; }
        public virtual DbSet<equipment> equipments { get; set; }
        public virtual DbSet<external_bill_addon_converters> external_bill_addon_converters { get; set; }
        public virtual DbSet<external_bill_files> external_bill_files { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<plan> plans { get; set; }
        public virtual DbSet<product_charge_records> product_charge_records { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<service_usage_offers> service_usage_offers { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<ticket_comments> ticket_comments { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<userclaim> userclaims { get; set; }
        public virtual DbSet<userlogin> userlogins { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<void_invoices> void_invoices { get; set; }
        public virtual DbSet<warning> warnings { get; set; }
        public virtual DbSet<calling_rates_voip> calling_rates_voip { get; set; }
    }
}
