//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OriEntities : DbContext
    {
        public OriEntities()
            : base("name=OriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<batch_job_execution> batch_job_execution { get; set; }
        public virtual DbSet<batch_job_execution_context> batch_job_execution_context { get; set; }
        public virtual DbSet<batch_job_instance> batch_job_instance { get; set; }
        public virtual DbSet<batch_step_execution> batch_step_execution { get; set; }
        public virtual DbSet<batch_step_execution_context> batch_step_execution_context { get; set; }
        public virtual DbSet<tm_billing_default_parameter> tm_billing_default_parameter { get; set; }
        public virtual DbSet<tm_billing_file_upload> tm_billing_file_upload { get; set; }
        public virtual DbSet<tm_contact_us> tm_contact_us { get; set; }
        public virtual DbSet<tm_customer> tm_customer { get; set; }
        public virtual DbSet<tm_customer_billing_log> tm_customer_billing_log { get; set; }
        public virtual DbSet<tm_customer_call_record> tm_customer_call_record { get; set; }
        public virtual DbSet<tm_customer_calling_record_callplus> tm_customer_calling_record_callplus { get; set; }
        public virtual DbSet<tm_customer_chorus_broadband_asid_record> tm_customer_chorus_broadband_asid_record { get; set; }
        public virtual DbSet<tm_customer_credit> tm_customer_credit { get; set; }
        public virtual DbSet<tm_customer_ddpay> tm_customer_ddpay { get; set; }
        public virtual DbSet<tm_customer_invoice> tm_customer_invoice { get; set; }
        public virtual DbSet<tm_customer_invoice_detail> tm_customer_invoice_detail { get; set; }
        public virtual DbSet<tm_customer_order> tm_customer_order { get; set; }
        public virtual DbSet<tm_customer_order_broadband_asid> tm_customer_order_broadband_asid { get; set; }
        public virtual DbSet<tm_customer_order_chorus_addon> tm_customer_order_chorus_addon { get; set; }
        public virtual DbSet<tm_customer_order_detail> tm_customer_order_detail { get; set; }
        public virtual DbSet<tm_customer_order_detail_delete_record> tm_customer_order_detail_delete_record { get; set; }
        public virtual DbSet<tm_customer_order_detail_recoverable_list> tm_customer_order_detail_recoverable_list { get; set; }
        public virtual DbSet<tm_customer_order_log> tm_customer_order_log { get; set; }
        public virtual DbSet<tm_customer_order_nz_calling_rates_setting> tm_customer_order_nz_calling_rates_setting { get; set; }
        public virtual DbSet<tm_customer_order_onsite> tm_customer_order_onsite { get; set; }
        public virtual DbSet<tm_customer_order_onsite_detail> tm_customer_order_onsite_detail { get; set; }
        public virtual DbSet<tm_customer_order_provision_checklist> tm_customer_order_provision_checklist { get; set; }
        public virtual DbSet<tm_customer_service_record> tm_customer_service_record { get; set; }
        public virtual DbSet<tm_customer_transaction> tm_customer_transaction { get; set; }
        public virtual DbSet<tm_defray_failure_record> tm_defray_failure_record { get; set; }
        public virtual DbSet<tm_early_termination_charge> tm_early_termination_charge { get; set; }
        public virtual DbSet<tm_equip> tm_equip { get; set; }
        public virtual DbSet<tm_equip_log> tm_equip_log { get; set; }
        public virtual DbSet<tm_equip_pattern> tm_equip_pattern { get; set; }
        public virtual DbSet<tm_hardware> tm_hardware { get; set; }
        public virtual DbSet<tm_manual_defray_log> tm_manual_defray_log { get; set; }
        public virtual DbSet<tm_manual_manipulation_record> tm_manual_manipulation_record { get; set; }
        public virtual DbSet<tm_notification> tm_notification { get; set; }
        public virtual DbSet<tm_plan> tm_plan { get; set; }
        public virtual DbSet<tm_provision_log> tm_provision_log { get; set; }
        public virtual DbSet<tm_termination_refund> tm_termination_refund { get; set; }
        public virtual DbSet<tm_ticket> tm_ticket { get; set; }
        public virtual DbSet<tm_ticket_comment> tm_ticket_comment { get; set; }
        public virtual DbSet<tm_user> tm_user { get; set; }
        public virtual DbSet<tm_vos_voip_call_record> tm_vos_voip_call_record { get; set; }
        public virtual DbSet<tm_voucher> tm_voucher { get; set; }
        public virtual DbSet<tm_voucher_banned_list> tm_voucher_banned_list { get; set; }
        public virtual DbSet<tm_voucher_file_upload> tm_voucher_file_upload { get; set; }
        public virtual DbSet<batch_job_execution_params> batch_job_execution_params { get; set; }
        public virtual DbSet<batch_job_execution_seq> batch_job_execution_seq { get; set; }
        public virtual DbSet<batch_job_seq> batch_job_seq { get; set; }
        public virtual DbSet<batch_step_execution_seq> batch_step_execution_seq { get; set; }
        public virtual DbSet<tm_call_international_rates> tm_call_international_rates { get; set; }
        public virtual DbSet<tm_vos_voip_rates> tm_vos_voip_rates { get; set; }
    }
}
