//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public bool IsBusiness { get; set; }
        public string BroadbandType { get; set; }
        public int PstnCount { get; set; }
        public int VoipCount { get; set; }
        public int MonthsOfContract { get; set; }
        public double MonthlyPrice { get; set; }
        public double NewConnectionCharge { get; set; }
        public double ModemPrice { get; set; }
        public bool IsPromotion { get; set; }
        public int DisplayPriority { get; set; }
        public string Memo { get; set; }
        public bool IsActive { get; set; }
    }
}
