//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.equipments = new HashSet<equipment>();
            this.product_charge_records = new HashSet<product_charge_records>();
            this.service_usage_offers = new HashSet<service_usage_offers>();
            this.services = new HashSet<service>();
        }
    
        public string Id { get; set; }
        public int AccountId { get; set; }
        public string Name { get; set; }
        public double BasePriceGSTExclusive { get; set; }
        public double DiscountRate { get; set; }
        public int NumberOfMonthPerCharge { get; set; }
        public Nullable<System.DateTime> ServiceGivenDate { get; set; }
        public Nullable<System.DateTime> ChargedToDate { get; set; }
        public bool IsTermed { get; set; }
        public Nullable<System.DateTime> TermStartDate { get; set; }
        public Nullable<int> MonthsOfTerm { get; set; }
        public bool IsOneOff { get; set; }
        public Nullable<System.DateTime> OneOffChargeDate { get; set; }
        public Nullable<bool> HasOneOffCharged { get; set; }
        public System.DateTime AppliedDate { get; set; }
        public int PrepayMonths { get; set; }
    
        public virtual account account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipment> equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_charge_records> product_charge_records { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service_usage_offers> service_usage_offers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service> services { get; set; }
    }
}
