//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_charge_records
    {
        public string Id { get; set; }
        public string ProductId { get; set; }
        public int AccountId { get; set; }
        public Nullable<System.DateTime> PreviousProductChargedToDate { get; set; }
        public Nullable<System.DateTime> CurrentProductChargedToDate { get; set; }
        public double AmountGSTExclusive { get; set; }
        public System.DateTime ChargedDate { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string Memo { get; set; }
    
        public virtual account account { get; set; }
        public virtual invoice invoice { get; set; }
        public virtual product product { get; set; }
    }
}
