//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_usage_offers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service_usage_offers()
        {
            this.calling_records = new HashSet<calling_records>();
        }
    
        public string Id { get; set; }
        public string ProductId { get; set; }
        public string ServiceType { get; set; }
        public string ServiceSubType { get; set; }
        public string Name { get; set; }
        public int Minutes { get; set; }
        public int DataFlow { get; set; }
        public bool Local { get; set; }
        public bool National { get; set; }
        public bool Mobile { get; set; }
        public string CallingRegionId { get; set; }
        public bool IsDeleted { get; set; }
        public int OperatorId { get; set; }
    
        public virtual calling_international_regions calling_international_regions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calling_records> calling_records { get; set; }
        public virtual product product { get; set; }
    }
}
