//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service()
        {
            this.addon_charge_records = new HashSet<addon_charge_records>();
            this.calling_charge_records = new HashSet<calling_charge_records>();
            this.calling_records = new HashSet<calling_records>();
        }
    
        public string Id { get; set; }
        public string ProductId { get; set; }
        public string Type { get; set; }
        public string SubType { get; set; }
        public string IdentityNumber { get; set; }
        public string BroadbandSVLAN { get; set; }
        public string BroadbandCVLAN { get; set; }
        public string BroadbandPPPoeLoginName { get; set; }
        public string BroadbandPPPoePassword { get; set; }
        public string VoipPassword { get; set; }
        public Nullable<System.DateTime> VoipAssignedDate { get; set; }
        public Nullable<System.DateTime> ReadyForServiceDate { get; set; }
        public string Status { get; set; }
        public bool IsDeleted { get; set; }
        public int OperatorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<addon_charge_records> addon_charge_records { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calling_charge_records> calling_charge_records { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calling_records> calling_records { get; set; }
        public virtual product product { get; set; }
    }
}
