//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_billing_file_upload
    {
        public int id { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public string upload_path { get; set; }
        public string upload_file_name { get; set; }
        public Nullable<bool> inserted_database { get; set; }
        public Nullable<int> upload_by { get; set; }
        public string billing_type { get; set; }
        public Nullable<System.DateTime> statement_date { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
    }
}
