//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_customer_order_detail_delete_record
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> detail_id { get; set; }
        public string detail_name { get; set; }
        public string detail_type { get; set; }
        public Nullable<int> executor_id { get; set; }
        public Nullable<System.DateTime> executed_date { get; set; }
        public string delete_reason { get; set; }
        public Nullable<bool> is_recoverable { get; set; }
    }
}
