//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_customer_order_onsite
    {
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string plan_name { get; set; }
        public Nullable<double> data_flow { get; set; }
        public Nullable<sbyte> plan_terms { get; set; }
        public string onsite_type { get; set; }
        public string onsite_status { get; set; }
        public Nullable<System.DateTime> onsite_date { get; set; }
        public Nullable<double> onsite_charge { get; set; }
        public string customer_type { get; set; }
        public string org_name { get; set; }
        public string org_type { get; set; }
        public string org_trading_name { get; set; }
        public string org_register_no { get; set; }
        public string holder_name { get; set; }
        public string holder_job_title { get; set; }
        public string holder_phone { get; set; }
        public string holder_email { get; set; }
        public string onsite_description { get; set; }
        public string pdf_path { get; set; }
    }
}
