//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_customer_order
    {
        public int id { get; set; }
        public string order_serial { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<double> order_total_price { get; set; }
        public Nullable<System.DateTime> order_create_date { get; set; }
        public string order_status { get; set; }
        public Nullable<System.DateTime> order_using_start { get; set; }
        public Nullable<System.DateTime> next_invoice_create_date { get; set; }
        public Nullable<System.DateTime> next_invoice_create_date_flag { get; set; }
        public string order_type { get; set; }
        public string order_broadband_type { get; set; }
        public string svlan { get; set; }
        public string cvlan { get; set; }
        public string transition_provider_name { get; set; }
        public string transition_account_holder_name { get; set; }
        public string transition_account_number { get; set; }
        public string transition_porting_number { get; set; }
        public Nullable<int> hardware_post { get; set; }
        public Nullable<System.DateTime> order_due { get; set; }
        public Nullable<int> pstn_count { get; set; }
        public Nullable<double> pstn_rental_amount { get; set; }
        public Nullable<int> term_period { get; set; }
        public string pppoe_loginname { get; set; }
        public string pppoe_password { get; set; }
        public Nullable<int> sale_id { get; set; }
        public string order_pdf_path { get; set; }
        public string credit_pdf_path { get; set; }
        public string signature { get; set; }
        public string optional_request { get; set; }
        public string broadband_asid { get; set; }
        public Nullable<System.DateTime> rfs_date { get; set; }
        public string previous_provider_invoice { get; set; }
        public Nullable<int> user_id { get; set; }
        public string ddpay_pdf_path { get; set; }
        public Nullable<bool> is_ddpay { get; set; }
        public string ordering_form_pdf_path { get; set; }
        public string receipt_pdf_path { get; set; }
        public string gift_pdf_path { get; set; }
        public Nullable<System.DateTime> disconnected_date { get; set; }
        public string connection_date { get; set; }
        public string contract { get; set; }
        public Nullable<int> inviter_customer_id { get; set; }
        public Nullable<int> inviter_user_id { get; set; }
        public Nullable<double> inviter_rate { get; set; }
        public Nullable<double> invitee_rate { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string address { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string customer_type { get; set; }
        public string org_name { get; set; }
        public string org_type { get; set; }
        public string org_trading_name { get; set; }
        public string org_register_no { get; set; }
        public Nullable<System.DateTime> org_incoporate_date { get; set; }
        public Nullable<int> org_trading_months { get; set; }
        public string holder_name { get; set; }
        public string holder_job_title { get; set; }
        public string holder_phone { get; set; }
        public string holder_email { get; set; }
        public string xero_invoice_status { get; set; }
        public Nullable<bool> is_send_xero_invoice { get; set; }
        public Nullable<double> checklist_progress { get; set; }
    }
}
