//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_customer
    {
        public int id { get; set; }
        public string login_name { get; set; }
        public string password { get; set; }
        public string md5_password { get; set; }
        public string user_name { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string cellphone { get; set; }
        public string status { get; set; }
        public string invoice_post { get; set; }
        public Nullable<System.DateTime> register_date { get; set; }
        public Nullable<System.DateTime> active_date { get; set; }
        public Nullable<double> balance { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public string driver_licence { get; set; }
        public string passport { get; set; }
        public string country { get; set; }
        public string company_name { get; set; }
        public string customer_type { get; set; }
        public string identity_type { get; set; }
        public string identity_number { get; set; }
        public string result { get; set; }
    }
}
