//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_contact_us
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string cellphone { get; set; }
        public string phone { get; set; }
        public string status { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> submit_date { get; set; }
        public Nullable<System.DateTime> respond_date { get; set; }
        public string respond_content { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
