//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_customer_order_detail
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string detail_name { get; set; }
        public string detail_desc { get; set; }
        public Nullable<double> detail_cost { get; set; }
        public Nullable<double> detail_price { get; set; }
        public Nullable<long> detail_data_flow { get; set; }
        public string detail_plan_status { get; set; }
        public string detail_plan_type { get; set; }
        public string detail_plan_sort { get; set; }
        public string detail_plan_group { get; set; }
        public string detail_plan_class { get; set; }
        public Nullable<double> detail_plan_new_connection_fee { get; set; }
        public Nullable<int> detail_term_period { get; set; }
        public Nullable<long> detail_topup_data_flow { get; set; }
        public Nullable<double> detail_topup_fee { get; set; }
        public string detail_plan_memo { get; set; }
        public Nullable<int> detail_unit { get; set; }
        public Nullable<int> detail_calling_minute { get; set; }
        public string detail_type { get; set; }
        public Nullable<int> detail_is_next_pay { get; set; }
        public Nullable<System.DateTime> detail_expired { get; set; }
        public Nullable<int> is_post { get; set; }
        public string hardware_comment { get; set; }
        public string track_code { get; set; }
        public string pstn_number { get; set; }
        public Nullable<int> user_id { get; set; }
        public string voip_password { get; set; }
        public Nullable<System.DateTime> voip_assign_date { get; set; }
        public Nullable<bool> is_nca { get; set; }
        public Nullable<int> to_nca_by_who { get; set; }
        public Nullable<int> equip_id { get; set; }
    }
}
