//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_customer_order_provision_checklist
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string payment_form { get; set; }
        public Nullable<bool> has_pstn { get; set; }
        public Nullable<bool> has_fax { get; set; }
        public Nullable<bool> has_voip { get; set; }
        public Nullable<sbyte> pstn_count { get; set; }
        public Nullable<sbyte> fax_count { get; set; }
        public Nullable<sbyte> voip_count { get; set; }
        public Nullable<bool> has_alarm { get; set; }
        public Nullable<bool> has_emergency { get; set; }
        public Nullable<bool> has_cctv { get; set; }
        public Nullable<bool> has_eftpos { get; set; }
        public Nullable<bool> has_smart_bundle { get; set; }
        public Nullable<bool> has_call_restrict { get; set; }
        public Nullable<bool> has_call_waiting { get; set; }
        public Nullable<bool> has_faxability { get; set; }
        public Nullable<bool> has_call_display { get; set; }
        public Nullable<bool> has_wire_maintenance { get; set; }
        public Nullable<bool> has_static_ip { get; set; }
        public Nullable<bool> has_dial_wrap { get; set; }
        public Nullable<sbyte> smart_bundle_count { get; set; }
        public Nullable<sbyte> call_restrict_count { get; set; }
        public Nullable<sbyte> call_waiting_count { get; set; }
        public Nullable<sbyte> faxability_count { get; set; }
        public Nullable<sbyte> call_display_count { get; set; }
        public Nullable<sbyte> wire_maintenance_count { get; set; }
        public Nullable<sbyte> static_ip_count { get; set; }
        public Nullable<sbyte> dial_wrap_count { get; set; }
        public Nullable<bool> has_router_post { get; set; }
        public Nullable<sbyte> router_post_count { get; set; }
        public Nullable<bool> has_svcv_lan { get; set; }
        public Nullable<bool> has_service_given { get; set; }
        public Nullable<bool> has_pstn_nca { get; set; }
        public Nullable<sbyte> pstn_nca_count { get; set; }
    }
}
