//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_customer_transaction
    {
        public long id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public Nullable<double> amount { get; set; }
        public string auth_code { get; set; }
        public string cardholder_name { get; set; }
        public string card_name { get; set; }
        public string card_number { get; set; }
        public string client_info { get; set; }
        public string currency_input { get; set; }
        public Nullable<double> amount_settlement { get; set; }
        public string expiry_date { get; set; }
        public string dps_txn_ref { get; set; }
        public string merchant_reference { get; set; }
        public string response_text { get; set; }
        public string success { get; set; }
        public string txnMac { get; set; }
        public string transaction_type { get; set; }
        public string transaction_sort { get; set; }
        public Nullable<int> executor { get; set; }
        public Nullable<int> inviter_id { get; set; }
    }
}
