//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_customer_credit
    {
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string card_type { get; set; }
        public string holder_name { get; set; }
        public string card_number { get; set; }
        public string security_code { get; set; }
        public string expiry_date { get; set; }
        public string order_ids { get; set; }
    }
}
