//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_customer_order_onsite_detail
    {
        public int id { get; set; }
        public Nullable<int> onsite_id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public Nullable<sbyte> unit { get; set; }
        public Nullable<double> price { get; set; }
    }
}
