//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_customer_invoice
    {
        public int id { get; set; }
        public string invoice_serial { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<double> amount_payable { get; set; }
        public Nullable<double> final_payable_amount { get; set; }
        public Nullable<double> amount_paid { get; set; }
        public Nullable<double> balance { get; set; }
        public string status { get; set; }
        public string memo { get; set; }
        public string invoice_pdf_path { get; set; }
        public Nullable<System.DateTime> paid_date { get; set; }
        public string paid_type { get; set; }
        public Nullable<int> last_invoice_id { get; set; }
        public string payment_status { get; set; }
        public Nullable<int> original_customer_id { get; set; }
        public Nullable<int> original_order_id { get; set; }
        public string invoice_type { get; set; }
        public Nullable<double> chorus_calling_credit { get; set; }
        public Nullable<double> chorus_calling_charge { get; set; }
        public Nullable<double> nca_calling_credit { get; set; }
        public Nullable<double> nca_calling_charge { get; set; }
        public Nullable<double> vos_calling_credit { get; set; }
        public Nullable<double> vos_calling_charge { get; set; }
        public string order_status { get; set; }
    }
}
