//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_customer_calling_record_callplus
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> length { get; set; }
        public string description { get; set; }
        public Nullable<double> charged_fee { get; set; }
        public string original_number { get; set; }
        public string destination_number { get; set; }
        public string type { get; set; }
        public Nullable<bool> used { get; set; }
        public Nullable<int> invoice_id { get; set; }
    }
}
