//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_early_termination_charge
    {
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> service_given_date { get; set; }
        public Nullable<System.DateTime> termination_date { get; set; }
        public Nullable<System.DateTime> legal_termination_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<double> overdue_extra_charge { get; set; }
        public Nullable<double> charge_amount { get; set; }
        public Nullable<double> total_payable_amount { get; set; }
        public Nullable<int> months_between_begin_end { get; set; }
        public Nullable<int> execute_by { get; set; }
        public string invoice_pdf_path { get; set; }
        public string status { get; set; }
    }
}
