//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_equip
    {
        public int id { get; set; }
        public string equip_name { get; set; }
        public string equip_type { get; set; }
        public string equip_purpose { get; set; }
        public string equip_sn { get; set; }
        public string equip_status { get; set; }
        public Nullable<int> order_detail_id { get; set; }
        public Nullable<System.DateTime> warehousing_date { get; set; }
    }
}
