//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_hardware
    {
        public int id { get; set; }
        public string hardware_name { get; set; }
        public string hardware_desc { get; set; }
        public string hardware_class { get; set; }
        public string hardware_type { get; set; }
        public string hardware_status { get; set; }
        public Nullable<double> hardware_price { get; set; }
        public Nullable<double> hardware_cost { get; set; }
        public string img1 { get; set; }
        public string img2 { get; set; }
        public string img3 { get; set; }
        public Nullable<bool> router_adsl { get; set; }
        public Nullable<bool> router_vdsl { get; set; }
        public Nullable<bool> router_ufb { get; set; }
        public Nullable<bool> support_pstn { get; set; }
        public Nullable<bool> support_voip { get; set; }
    }
}
