//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_plan
    {
        public int id { get; set; }
        public string plan_name { get; set; }
        public string plan_desc { get; set; }
        public Nullable<double> plan_price { get; set; }
        public Nullable<double> original_price { get; set; }
        public Nullable<long> data_flow { get; set; }
        public Nullable<long> data_flow_k { get; set; }
        public string plan_status { get; set; }
        public string plan_type { get; set; }
        public string plan_sort { get; set; }
        public string plan_group { get; set; }
        public string plan_class { get; set; }
        public Nullable<double> plan_new_connection_fee { get; set; }
        public string memo { get; set; }
        public Nullable<int> plan_prepay_months { get; set; }
        public Nullable<int> pstn_count { get; set; }
        public Nullable<double> pstn_rental_amount { get; set; }
        public Nullable<int> term_period { get; set; }
        public string img1 { get; set; }
        public string img2 { get; set; }
        public string img3 { get; set; }
        public Nullable<bool> promotion { get; set; }
        public Nullable<int> place_sort { get; set; }
        public Nullable<double> jackpot_fee { get; set; }
        public Nullable<double> transition_fee { get; set; }
        public Nullable<int> voip_count { get; set; }
    }
}
