//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_provision_log
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> process_datetime { get; set; }
        public string order_sort { get; set; }
        public Nullable<int> order_id_customer { get; set; }
        public Nullable<int> order_id_chorus { get; set; }
        public string process_way { get; set; }
        public string process_memo { get; set; }
    }
}
