//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_ticket_comment
    {
        public int id { get; set; }
        public Nullable<int> ticket_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
