//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_termination_refund
    {
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<double> product_monthly_price { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> termination_date { get; set; }
        public string refund_bank_account_number { get; set; }
        public string refund_bank_account_name { get; set; }
        public Nullable<double> refund_amount { get; set; }
        public Nullable<int> execute_by { get; set; }
        public string refund_pdf_path { get; set; }
        public string status { get; set; }
        public string product_name { get; set; }
        public Nullable<int> days_between_end_last { get; set; }
        public Nullable<System.DateTime> last_date_of_month { get; set; }
    }
}
