//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_vos_voip_rates
    {
        public string area_prefix { get; set; }
        public string rate_type { get; set; }
        public string area_name { get; set; }
        public Nullable<double> billed_rate { get; set; }
        public Nullable<double> billed_cycle { get; set; }
        public Nullable<double> billed_per_min { get; set; }
    }
}
