//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_voucher
    {
        public string serial_number { get; set; }
        public string card_number { get; set; }
        public Nullable<double> face_value { get; set; }
        public string status { get; set; }
        public string comment { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string post_to { get; set; }
        public Nullable<int> order_id { get; set; }
    }
}
