//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_voucher_banned_list
    {
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> attempt_times { get; set; }
        public Nullable<System.DateTime> forbad_date { get; set; }
    }
}
