//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_voucher_file_upload
    {
        public int id { get; set; }
        public string file_name { get; set; }
        public string file_path { get; set; }
        public string status { get; set; }
        public Nullable<int> inserted_by { get; set; }
        public Nullable<int> upload_by { get; set; }
        public Nullable<System.DateTime> inserted_date { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
    }
}
