//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class void_invoices
    {
        public string id { get; set; }
        public int InvoiceId { get; set; }
        public int VoidBy { get; set; }
        public System.DateTime VoidDate { get; set; }
        public string JsonData { get; set; }
    }
}
