//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q.xISP.Transfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class warning
    {
        public string Id { get; set; }
        public string Module { get; set; }
        public string Operate { get; set; }
        public string Message { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ClearBy { get; set; }
        public Nullable<System.DateTime> ClearDate { get; set; }
    }
}
